spring:

  datasource:
    # ????????? ?????????????? ???????????? DataSource
    enabled: false
  autoconfigure:
    # ????????? ?????????????? ???????????? ??? ???? DataSource, JdbcTemplate ? JPA
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    server:
      port: 9001


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
